### ISSUE TITLE
Error: unknown column "tau" 

### ISSUE THREAD

**Issue by jhemberger** [Aariq/bumbl#30]
Howdy!  I'm excited to finally be able to start playing with this package.   I'm trying to fit models in accordance with your readme, but having some issues.  The bumbl function keeps throwing an error saying, "unknown column `tau`".  Like you, I have my t set to equal the week of the experiment.  The error is preceded by a statement for each of my colonies stating that it cannot find starting values.  Below is the function call and the `head()` of my data

`bumbl(colmass.df, colonyID = colony_id, t = week, formula = mass.dif ~ week, augment = TRUE)`

![Screen Shot 2019-11-16 at 5 27 09 PM](https://user-images.githubusercontent.com/24531145/69000504-53aa2e80-0896-11ea-9a88-4fd02e3ea656.png)

**Comment by Aariq** [comment]
When did you install `bumbl`? I just updated it earlier this week, although I'm not sure it would change anything in this example...
The warning about not being able to find starting values sounds like it's coming from `glm()` and I'm not sure why.

**Comment by jhemberger** [comment]
Just installed today.  It's as if the `glm()` call is looking for a column named "tau" instead of "week"

**Comment by Aariq** [comment]
I'm at EntSoc this week (any chance you're here too?), but I'll take a look at it when I get back and see if I can reproduce it.  Thanks for trying it out!

**Comment by jhemberger** [comment]
Unfortunately I am not going this year - opted out to stay and finish thesis!  No problem, I'll watch this thread.  Feel free to holler at my if you want some additional beta testing - I told Elizabeth at BOMBUSS I'd be happy to do so.

**Comment by Aariq** [comment]
Note to self:  Check out `glm2` package and see if it might be more stable to finding starting values.

**Comment by Aariq** [comment]
I'm not sure, but I suspect it has something to do with you having two data points of mass for each week.  Try just using date as the response variable and time variable.  I agree the "unknown column tau" is misleading, so I'm going to work on a better error message for situations when the underlying glm() fails.
